module.exports = {
  docsSidebar: [
    'intro',
    'commercial-trust',
    'architecture',
    'case-studies-validation',
    'platform-guide',
    'malware-analysis',
    'attack-simulation',
    'visual-guide',
    'full-flow',
    'capabilities',
    'observability-security-validation',
    'getting-started',
    'functionality-parity',
    {
      type: 'category',
      label: 'Comparisons',
      items: [
        'comparisons/overview',
        'comparisons/opencti',
        'comparisons/misp',
        'comparisons/attack-navigator',
        'comparisons/atomic-red-team',
        'comparisons/malware-sandboxes',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      items: [
        'use-cases',
        'use-cases/simple-check-an-ioc',
        'use-cases/simple-open-actor-profile',
        'use-cases/simple-show-actor-on-matrix',
        'use-cases/simple-search-ioc-library',
        'use-cases/simple-sync-threatfox',
        'use-cases/simple-import-navigator-layer',
        'use-cases/simple-export-pdf-report',
        'use-cases/simple-run-selftest',
        'use-cases/simple-add-custom-ioc-feed',
        'use-cases/simple-open-troubleshooting',
        'use-cases/intermediate-map-report-to-attack',
        'use-cases/intermediate-compare-incident-to-actors',
        'use-cases/intermediate-build-sector-brief',
        'use-cases/intermediate-enrich-actor-iocs',
        'use-cases/intermediate-import-misp-json',
        'use-cases/intermediate-pull-taxii-stix',
        'use-cases/intermediate-sync-yara-sigma',
        'use-cases/intermediate-compare-two-reports',
        'use-cases/intermediate-review-coverage-gap',
        'use-cases/intermediate-use-local-llm',
        'use-cases/investigation-ransomware-intrusion',
        'use-cases/investigation-cloud-incident',
        'use-cases/investigation-apt-campaign-cluster',
        'use-cases/investigation-malware-family',
        'use-cases/investigation-third-party-report-validation',
        'use-cases/defense-mitre-coverage-baseline',
        'use-cases/defense-sector-detection-roadmap',
        'use-cases/defense-ioc-enrichment-pipeline',
        'use-cases/defense-detection-content-from-intel',
        'use-cases/defense-executive-risk-coverage-report',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: ['operations/operations-overview', 'operations/intelligence-pipeline'],
    },
    {
      type: 'category',
      label: 'AI Analysis',
      items: [
        'ai-analysis/overview',
        'ai-analysis/chat-assistant',
        'ai-analysis/domains',
      ],
    },
    {
      type: 'category',
      label: 'Navigator',
      items: [
        'navigator/overview',
        'navigator/layers',
        'navigator/import-export',
        'navigator/ttp-details',
      ],
    },
    {
      type: 'category',
      label: 'ATT&CK Group Library',
      items: [
        'apt-library/overview',
      ],
    },
    {
      type: 'category',
      label: 'Compare',
      items: [
        'compare/overview',
        'compare/groups',
        'compare/campaigns',
        'compare/reports',
        'compare/group-vs-group',
      ],
    },
    'two-databases',
    'attack-data-model',
    'cve-cvss-intelligence',
    'generating-reports',
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/overview',
        'api/analyze',
        'api/layers',
        'api/compare',
        'api/export',
        'api/sync',
      ],
    },
    'tips',
    'evaluation',
    'security',
    'roadmap',
  ],
};
