module.exports = {
  docsSidebar: [
    'intro',
    'getting-started',
    'functionality-parity',
    {
      type: 'category',
      label: 'Use Cases',
      items: [
        'use-cases',
        'use-cases/map-threat-report-to-attack',
        'use-cases/client-facing-cti-briefing',
        'use-cases/compare-incident-to-apt-groups',
        'use-cases/compare-threat-reports',
        'use-cases/cti-to-detection-backlog',
        'use-cases/attack-navigator-layers',
        'use-cases/detection-coverage-gaps',
        'use-cases/sector-actor-relevance',
        'use-cases/sector-threat-model',
        'use-cases/actor-ioc-enrichment',
        'use-cases/central-ioc-library',
        'use-cases/virustotal-ioc-enrichment',
        'use-cases/otx-malpedia-threatfox-context',
        'use-cases/custom-private-feeds',
        'use-cases/stix-taxii-exchange',
        'use-cases/misp-json-import',
        'use-cases/sigma-yara-rule-feeds',
        'use-cases/sandbox-malware-behavior',
        'use-cases/extract-iocs-from-reports',
        'use-cases/dfir-report-examples',
      ],
    },
    {
      type: 'category',
      label: 'Operations',
      items: ['operations/operations-overview', 'operations/intelligence-pipeline'],
    },
    {
      type: 'category',
      label: 'AI Analysis',
      items: [
        'ai-analysis/overview',
        'ai-analysis/chat-assistant',
        'ai-analysis/domains',
      ],
    },
    {
      type: 'category',
      label: 'Navigator',
      items: [
        'navigator/overview',
        'navigator/layers',
        'navigator/import-export',
        'navigator/ttp-details',
      ],
    },
    {
      type: 'category',
      label: 'ATT&CK Group Library',
      items: [
        'apt-library/overview',
      ],
    },
    {
      type: 'category',
      label: 'Compare',
      items: [
        'compare/overview',
        'compare/groups',
        'compare/campaigns',
        'compare/reports',
        'compare/group-vs-group',
      ],
    },
    'two-databases',
    'generating-reports',
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/overview',
        'api/analyze',
        'api/layers',
        'api/compare',
        'api/export',
        'api/sync',
      ],
    },
    'tips',
    'evaluation',
    'security',
    'roadmap',
  ],
};
